apiVersion: apps/v1
kind: Deployment
metadata:
  name: mapnextgen-deployment
spec:
  template:
    spec:
      containers:
      - name: mapnextgen
        image: ascomappsuite.azurecr.io/nordics/mapnextgen:latest
        envFrom:
        - configMapRef:
            name: mykustom-map
